/*
 * parse_json.js is build to ingest JSON files
 *
 * provides url to json record (var json_address)
 * function will open that file and parse some (not all) available fields from the JSON export
 * built for JSON records generated by DEIMS-SDR (https://deims.org/api)
 *
 * is currently still heavily intersected with the index.html :(
 * might be fixed in future versions
 *
 */	
	
function parse_json(json_address) {
	
	var x = new XMLHttpRequest();
	x.open("GET", json_address, true);
	x.onreadystatechange = function () {
		// on success, do the parsing
		if (x.readyState == 4 && x.status == 200) {
			var jsonObj = JSON.parse(x.responseText);
		
			resize_elements();
			
			var uuid = jsonObj["id"]["suffix"];
				
			// Define side variable; Clear previous text
			var sidebar_object_dom = document.getElementById('detailed_information');
			sidebar_object_dom.innerHTML = "";
			// Reset scrollbar
			$("#detailed_information").offset().top;
			
			// Title
			sidebar_object_dom.innerHTML += "<h1>" + jsonObj["title"] + "</h1>";
			sidebar_object_dom.innerHTML += "<p>" + "<b>DEIMS.iD:</b> <a href='https://deims.org/" + uuid + "' target='_blank' class='no_underline_link'>https://deims.org/" + uuid + "<sup><i class='fa fa-external-link' aria-hidden='true'></i></sup></a></p>";
			
			// description
			if (jsonObj["attributes"]["general"]["abstract"]) {
				sidebar_object_dom.innerHTML += "<b>Description: </b>" + jsonObj["attributes"]["general"]["abstract"] + "<br>";
			}
				
			// media monitored
			if (jsonObj["attributes"]["environmentalCharacteristics"]["geoBonBiome"] != null) {		
				sidebar_object_dom.innerHTML += "<br><b>media monitored: </b>";	
				// styled icons		
				var geobonbiome = jsonObj["attributes"]["environmentalCharacteristics"]["geoBonBiome"];
				for (let i = 0; i < geobonbiome.length; i++) {
					switch(geobonbiome[i]) {
						case "Terrestrial":
							sidebar_object_dom.innerHTML += "Terrestrial <i class='fa fa-tree' aria-hidden='true'></i><br>";
							break;
						case "Fresh water rivers":
							sidebar_object_dom.innerHTML += "Fresh Water Rivers <i class='fa fa-tint' aria-hidden='true'></i><br>";
							break;
						case "Fresh water lakes":
							sidebar_object_dom.innerHTML += "Fresh Water Lakes <i class='fa fa-tint' aria-hidden='true'></i><br>";
							break;
						case "Marine":
							sidebar_object_dom.innerHTML += "Marine <i class='fa fa-tint' aria-hidden='true'></i><br>";
							break;
						case "Coastal":
							sidebar_object_dom.innerHTML += "Coastal <i class='fa fa-tint' aria-hidden='true'></i><br>";
							break;
					}
				}
			}
			
			// onlineResource
			if (jsonObj["attributes"]["contact"]["siteUrl"] != null) {
				sidebar_object_dom.innerHTML += '<br><b>onlineResource(s):</b><br>';
				for (x in jsonObj["attributes"]["contact"]["siteUrl"]) {
					// check for content and skip the links to DEIMS as they are already listed below the title
					if (jsonObj["attributes"]["contact"]["siteUrl"][x]["uri"] != "" && !_.includes(jsonObj["attributes"]["contact"]["siteUrl"][x]["uri"], "https://deims.org")) {
						var online_resource_url = jsonObj["attributes"]["contact"]["siteUrl"][x]["value"];
						var url_title = jsonObj["attributes"]["contact"]["siteUrl"][x]["title"];
						if (url_title) {
							sidebar_object_dom.innerHTML += "<a href=" + online_resource_url + " target='_blank' class='no_underline_link'>" + url_title + "<sup><i class='fa fa-external-link' aria-hidden='true'></i></sup></a><br>";
						}
						else {
							sidebar_object_dom.innerHTML += "<a href=" + online_resource_url + " target='_blank' class='no_underline_link'>" + online_resource_url + "<sup><i class='fa fa-external-link' aria-hidden='true'></i></sup></a><br>";
						}
					}
				}
			}	
			
			// Observing capabilities
			if (jsonObj["attributes"]["focusDesignScale"]["parameters"] != null) {
				var list_of_parameters = '';
				sidebar_object_dom.innerHTML += '<br><b>ObservingCapabilities: </b>';
				for (x in jsonObj["attributes"]["focusDesignScale"]["parameters"]) {
					if (x["label"] != "" ) {
						list_of_parameters += jsonObj["attributes"]["focusDesignScale"]["parameters"][x]["label"] + "; ";
					}
				}
				sidebar_object_dom.innerHTML += list_of_parameters.slice(0, -2) + "<br>";
			}

			// hasObservation
			if (jsonObj["attributes"]["relatedResources"] != null) {
				sidebar_object_dom.innerHTML += "<br><b>hasObservation(s):</b><br>";
				
				for (x in jsonObj["attributes"]["relatedResources"]) {
					
						var hasObservation_url = jsonObj["attributes"]["relatedResources"][x]["id"]["prefix"] + jsonObj["attributes"]["relatedResources"][x]["id"]["suffix"];	
						var hasObservation_title = jsonObj["attributes"]["relatedResources"][x]["title"];			
						sidebar_object_dom.innerHTML += "<a id="+ hasObservation_url +" href='#' class='obs_link no_underline_link' data-bs-toggle='modal' data-bs-target='#observation_modal'>" + hasObservation_title + "</a><br>";
					
				}
	
			}
	
			// responsibleParty
			if (jsonObj["attributes"]["contact"]["siteManager"] != null) {
				sidebar_object_dom.innerHTML += '<br><b>responsibleParties:</b><br>';
				
				for (x in jsonObj["attributes"]["contact"]["siteManager"]) {
					sidebar_object_dom.innerHTML += jsonObj["attributes"]["contact"]["siteManager"][x]["name"] + "<br>";
				}
			
			}
					
			// belongsTo
			if (jsonObj["attributes"]["affiliation"]["networks"] != null || jsonObj["attributes"]["affiliation"]["project"] != null ) {
			
				sidebar_object_dom.innerHTML += '<br><b>belongsTo:</b><br>';
				
				if (jsonObj["attributes"]["affiliation"]["networks"] != null) {
					for (x in jsonObj["attributes"]["affiliation"]["networks"]) {

						var title = jsonObj["attributes"]["affiliation"]["networks"][x]["network"]["name"];
						var url = "https://deims.org/networks/" + jsonObj["attributes"]["affiliation"]["networks"][x]["network"]["id"]["suffix"];
						sidebar_object_dom.innerHTML += '<a href="' + url + '" target="_blank" class="no_underline_link">' + title + '<sup><i class="fa fa-external-link" aria-hidden="true"></i></sup></a>';
						if (jsonObj["attributes"]["affiliation"]["networks"][x]["verified"] == false) {
							sidebar_object_dom.innerHTML += " (not verified)";
						}
						sidebar_object_dom.innerHTML += "<br>";

					}
				}
				
				if (jsonObj["attributes"]["affiliation"]["projects"] != null) {
					var list_of_projects = '';
					for (x in jsonObj["attributes"]["affiliation"]["projects"]) {
						list_of_projects += jsonObj["attributes"]["affiliation"]["projects"][x]["label"] + ", ";
					}
					sidebar_object_dom.innerHTML += "<br>";
					sidebar_object_dom.innerHTML += list_of_projects.slice(0, -2) + "<br>";
				}

			} 
			
			
			
			var related_locations = jsonObj["attributes"]["geographic"]["relatedLocations"];
			
			if (related_locations) { 
				sidebar_object_dom.innerHTML += '<div id ="locations_div"></div>';
			}
		
			// has EuroCordex model data
			if (uuid in eurocordex_uuid_list) {
				sidebar_object_dom.innerHTML += "<br><b>There is EURO-CORDEX climate scenario data available for this site:</b><br>";
				var table_string = '<table style="width:100%">';

					table_string += '<tr>';
						table_string += '<td>Projected Near Surface Specific Humidity Change</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_huss_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_huss_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_huss_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_huss_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank"> ' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_huss_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_huss_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank"> ' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Precipitation Change</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_pr_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_pr_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_pr_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_pr_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_pr_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_pr_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Sea Level Pressure Change</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_psl_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_psl_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_psl_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_psl_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_psl_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_psl_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Surface Downwelling Shortwave Radiation</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_rsds_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_rsds_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_rsds_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_rsds_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_rsds_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_rsds_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Near-Surface Wind Speed</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_sfcWind_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_sfcWind_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_sfcWind_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_sfcWind_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_sfcWind_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_sfcWind_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Near-Surface Air Temperature</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tas_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_tas_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tas_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_tas_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tas_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_tas_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Daily Maximum Near-Surface Air Temperature</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmax_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_tasmax_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmax_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_tasmax_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmax_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_tasmax_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

					table_string += '<tr>';
						table_string += '<td>Projected Daily Minimum Near-Surface Air Temperature</td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmin_EUR-11_rcp26/' + uuid + '.EURO-CORDEX_tasmin_EUR-11_rcp26.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP26</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmin_EUR-11_rcp45/' + uuid + '.EURO-CORDEX_tasmin_EUR-11_rcp45.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP45</a></td>';
						table_string += '<td><a class="no_underline_link" href="https://deims.org/export/eurocordex/eLTER_site_data.EURO-CORDEX_tasmin_EUR-11_rcp85/' + uuid + '.EURO-CORDEX_tasmin_EUR-11_rcp85.dataV2018-02-07_procV2019-05-21_plotV2019-07-29.png" target="_blank">' + 'RCP85</a></td>';
					table_string += '</tr>';

				table_string += '</table><br>';
				table_string += '<div>You can also <a class="no_underline_link" target="_blank" href="';
				table_string += eurocordex_uuid_list[uuid];
				table_string += '">download the entire climate scenario dataset for this site</a> from the EUDAT B2SHARE data store.</div>' ;
			
				sidebar_object_dom.innerHTML += table_string;
				
			}
			
			sidebar_object_dom.innerHTML += "<br>";
			
			var site_boundaries = jsonObj["attributes"]["geographic"]["boundaries"];
			
			// turn location layer switcher invisible
			location_layers_invisible();
		
			// if there is no boundary information available
			if (!site_boundaries) {
				$.notify("There is no boundary information available for this site :(", "info");
				return;
			}
			
			// add related locations
			
			if (related_locations) {
				
				// related Locations
				var locations_container = document.getElementById("locations_div");
				locations_container.innerHTML += '<br><b>Related Locations:</b><br>';
			
			    var f = (function(){
		
					var xhr = [], i;
					for (i = 0; i < related_locations.length; i++) { //for loop
						(function(i){
							xhr[i] = new XMLHttpRequest();
							url = "https://deims.org/api/locations/" + related_locations[i]['id']['suffix'];
							xhr[i].open("GET", url, true);
							xhr[i].onreadystatechange = function(){
								if (xhr[i].readyState === 4 && xhr[i].status === 200){
									var location_json = JSON.parse(xhr[i].responseText);
									var format = new ol.format.GeoJSON();
									var feature = format.readFeature(location_json, {
										id: location_json['properties']['id']['suffix'],
										dataProjection: 'EPSG:4326',
											featureProjection: 'EPSG:3857'
									});
									
									locations_container.innerHTML += '<a class="no_underline_link" href="https://www.deims.org/locations/' + location_json['properties']['id']['suffix'] + '" target="_blank">' + location_json['properties']['title'] + '<sup><i class="fa fa-external-link" aria-hidden="true"></i></sup></a>';
									
									if (location_json['properties']['locationType']) {
										locations_container.innerHTML += ' (' + location_json['properties']['locationType']['label'] + ')';
										// add related locations
										switch (location_json['properties']['locationType']['label']) {
											case 'Hydrological Catchment':
												hydrological_catchment_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_hydro').css("visibility", "visible");
												$('#loc_type_hydro').css("display", "block");
												break;
											case 'Sampling Area':
												sampling_area_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_sampling').css("visibility", "visible");
												$('#loc_type_sampling').css("display", "block");
												break;
											case 'Equipment Location':
												equipment_location_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_equipment').css("visibility", "visible");
												$('#loc_type_equipment').css("display", "block");
												break;
											case 'e-shape':
												eshape_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_eshape').css("visibility", "visible");
												$('#loc_type_eshape').css("display", "block");
												break;
											case 'e-shape':
												eshape_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_eshape').css("visibility", "visible");
												$('#loc_type_eshape').css("display", "block");
												break;
											case 'Air Shed':
												airshed_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_airshed').css("visibility", "visible");
												$('#loc_type_airshed').css("display", "block");
												break;
											case 'Model Area':
												model_area_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_model').css("visibility", "visible");
												$('#loc_type_model').css("display", "block");
												break;	
											case 'Socio-ecological reference area':
												socio_ecological_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_socioecological').css("visibility", "visible");
												$('#loc_type_socioecological').css("display", "block");
												break;
											case 'not applicable':
												other_locations_source.addFeature(feature);
												$('#legend_locations_container').css("visibility", "visible");
												$('#loc_type_other').css("visibility", "visible");
												$('#loc_type_other').css("display", "block");
												break;
										}
									}
									else {
										other_locations_source.addFeature(feature);
										$('#legend_locations_container').css("visibility", "visible");
										$('#loc_type_other').css("visibility", "visible");
										$('#loc_type_other').css("display", "block");
									}
									locations_container.innerHTML += '<br>';
									
								}
								
							};
							
							xhr[i].send();
						})(i);	
					}
				})();
				
			}
			else {
				$('#legend_locations_container').css("visibility", "hidden");
			}
				
			// this part reads the geometry from the record and adds it to the map;
			
			// close popup
			overlay.setPosition(undefined);
			closer.blur();
				
			var format = new ol.format.WKT();

			var feature = format.readFeature(site_boundaries, {
				dataProjection: 'EPSG:4326',
				featureProjection: 'EPSG:3857'
			});
			
			vectorSource.addFeature(feature);
			
			var zoom_polygon = /** @type {ol.geom.SimpleGeometry} */ (feature.getGeometry());
			var zoom_extent = zoom_polygon.getExtent();
					
			view.fit(zoom_extent, {duration: 1000, padding: [50, 50, 50, 50]});
			
		} 
		
		// if there is something wrong with the JSON
		if (x.readyState == 4 && x.status == 500) {
			$.notify("The JSON record could not be loaded :(", {position:"top right"}, "error");		
			return;
		}
		  
	};
	
	x.send(null);
		
	return true;       
	
}
